title: KalaneaArt
url: https://kalaneaart.com
baseurl: 

author: Abraham Abdala
description: "Powered by Jekyll and GitHub Pages"

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  pondi:
    output: true
  kochi:
    output: true
  rj_women:
    output: true
  venice:
    output: true
  patriarchs:
    output: true
  rimi:
    output: true
  london:
    output: true
  mumbai:
    output: true
  market:
    output: true
  flowers:
    output: true
  animals:
    output: true
  warriors:
    output: true 

markdown: kramdown
kramdown:
  input: GFM
