# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:       "Kalanea Art"
description: "Powered by Jekyll and GitHub Pages"


author:
  fullname: Abraham Abdala  
  email: kalaneaart@gmail.com

imagesurl: "/assets/img/portfolio/img/"
thumbsurl: "/assets/img/portfolio/thumbs/"
