#-------------------------------
# General Site Settings
menu:
- {name: 'Collections', url: ''}
#- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}
#- {name: 'Morro', url: 'index'}

#-------------------------------
# Projects Section
projects:
- {name: 'What can we learn from',   url: 'proj-1'}
- {name: 'Warriors',   url: 'proj-2'}
- {name: 'Animals', url: 'proj-3'}
#- {name: 'Project Four',  url: 'proj-4'}
#- {name: 'Project Five',  url: 'proj-5'}

#-------------------------------
# What can we learn from Section
whatcanwelearnfrom:
- {name: 'Judges',   url: 'Subproj-1'}
- {name: 'Prophets',   url: 'Subproj-2'}
- {name: 'Patriarchs', url: 'Subproj-3'}
#- {name: 'Project Four',  url: 'proj-4'}
#- {name: 'Project Five',  url: 'proj-5'}

#-------------------------------
# Judges Section
judges:
- {name: 'Othniel',   url: 'Othniel'}
- {name: 'Ehud',   url: 'Ehud'}
- {name: 'Shamgar', url: 'Shamgar'}
- {name: 'Othniel',   url: 'Othniel'}
- {name: 'Ehud',   url: 'Ehud'}
- {name: 'Shamgar', url: 'Shamgar'}
- {name: 'Othniel',   url: 'Othniel'}
- {name: 'Ehud',   url: 'Ehud'}
- {name: 'Shamgar', url: 'Shamgar'}
- {name: 'Othniel',   url: 'Othniel'}
- {name: 'Ehud',   url: 'Ehud'}
- {name: 'Shamgar', url: 'Shamgar'}


#-------------------------------
# Prophets Section
prophets:
- {name: 'Samuel',   url: 'Samuel'}
- {name: 'Elijah',   url: 'Elijah'}
- {name: 'Elisha', url: 'Elisha'}
- {name: 'Jonah',   url: 'Jonah'}
- {name: 'Isaiah',   url: 'Isaiah'}
- {name: 'Jeremiah', url: 'Jeremiah'}

#-------------------------------
# Patriarchs Section
patriarchs:
- {name: 'Abraham',   url: 'Abraham'}
- {name: 'Isaac',   url: 'Isaac'}
- {name: 'Jacob', url: 'Jacob'}


#-------------------------------
# Warriors Section
warriors:
- {name: 'Jaguar Warrior',   url: 'JaguarWarrior'}
- {name: 'Pretorian Guard',   url: 'PretorianGuard'}
- {name: 'Templar Knight', url: 'TemplarKnight'}

#-------------------------------
# Warriors Section
animals:
- {name: 'Lion',   url: 'Feline1'}
- {name: 'Tiger',   url: 'Feline2'}
- {name: 'Toucan', url: 'Bird1'}


#-------------------------------
# Contact Section

social:
#- {icon: 'twitter',   link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/kalaneaart'}
#- {icon: 'github',    link: 'https://github.com/lenpaul'}
#- {icon: 'linkedin',  link: 'https://linkedin.com/in/lenpaul'}
#- {icon: 'envelope',  link: 'mailto:kalaneaart@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
