#-------------------------------
# General Site Settings
facts:
  IMG_7596.jpg: 'These are freaking daisies'
  IMG_7613.jpg: 'These are freaking roses'
  IMG_7659.jpg: 'These is a water lili'
  IMG_7672.jpg: 'These are girasoles'
  IMG_7753.jpg: 'These are water lilies gallery'





#- {name: 'IMG_7596.jpg', description: 'These are freaking daisies'}



#-------------------------------
# Contact Section

social:
#- {icon: 'twitter',   link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/kalaneaart'}
#- {icon: 'github',    link: 'https://github.com/lenpaul'}
#- {icon: 'linkedin',  link: 'https://linkedin.com/in/lenpaul'}
#- {icon: 'envelope',  link: 'mailto:kalaneaart@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
